server:
  port: ${GATEWAY_PORT:8000}

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:game-cellar}/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info